site_name: StackHPC Release Train
site_url: https://stackhpc.github.io/stackhpc-release-train/
repo_url: https://github.com/stackhpc/stackhpc-release-train/
theme:
  name: material
  palette:
    scheme: default
    primary: red
  features:
    - navigation.instant
    - navigation.sections
markdown_extensions:
  # From mkdocs-material: allow !!! note.
  - admonition
  - toc:
      permalink: True
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Overview: index.md
  - Architecture: architecture/index.md
  - Usage:
      Content management HOWTO: usage/content-howto.md
      Content management workflows: usage/content-workflows.md
      Access control: usage/access.md
      Source code CI: usage/source-code-ci.md
  - Operations:
      Ark: operations/ark.md
      Test Pulp: operations/test-pulp.md
      Vault: operations/vault.md
      GitHub: operations/github.md
  - Contributing: contributing.md
