---
- name: Display Pulp distributions, publications & repositories
  hosts: localhost
  gather_facts: True
  vars:
    pulp_url: "{{ dev_pulp_url }}"
    pulp_username: "{{ dev_pulp_username }}"
    pulp_password: "{{ dev_pulp_password }}"
  tasks:
    - name: Query Deb repositories
      pulp.squeezer.deb_repository:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_deb_repos_list

    - name: Query Deb publications
      pulp.squeezer.deb_publication:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_deb_pubs_list

    - name: Query Deb verbatim publications
      pulp.squeezer.deb_publication:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
        mode: verbatim
      register: pulp_deb_verbatim_pubs_list

    - name: Query Deb distributions
      pulp.squeezer.deb_distribution:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_deb_dists_list

    - name: Display Deb distributions
      vars:
        pub: "{{ (pulp_deb_pubs_list.publications + pulp_deb_verbatim_pubs_list.publications) | selectattr('pulp_href', 'equalto', item.publication) | first }}"
        repo: "{{ pulp_deb_repos_list.repositories | selectattr('pulp_href', 'equalto', pub.repository) | first }}"
        info:
          repo: "{{ repo }}"
          pub: "{{ pub }}"
          dist: "{{ item }}"
      debug:
        var: info
      loop: "{{ pulp_deb_dists_list.distributions }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Query RPM repositories
      pulp.squeezer.rpm_repository:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_rpm_repos_list

    - name: Query RPM publications
      pulp.squeezer.rpm_publication:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_rpm_pubs_list

    - name: Query RPM distributions
      pulp.squeezer.rpm_distribution:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_rpm_dists_list

    - name: Display RPM distributions
      vars:
        pub: "{{ pulp_rpm_pubs_list.publications | selectattr('pulp_href', 'equalto', item.publication) | first }}"
        repo: "{{ pulp_rpm_repos_list.repositories | selectattr('pulp_href', 'equalto', pub.repository) | first }}"
        info:
          repo: "{{ repo }}"
          pub: "{{ pub }}"
          dist: "{{ item }}"
      debug:
        var: info
      loop: "{{ pulp_rpm_dists_list.distributions }}"
      loop_control:
        label: "{{ item.name }}"
