---
# This playbook queries the Pulp repository versions defined in a Kayobe
# configuration repository (in etc/kayobe/pulp-repo-versions.yml). It then
# updates those versions based on the latest versions in dev Pulp (via the
# test_pulp_repository_deb_repo_versions and
# test_pulp_repository_rpm_repo_versions variables, which are populated in
# test-pulp-repo-version-query.yml).

# Query existing Kayobe config repo versions.
- import_playbook: kayobe-repo-version-query.yml

- name: Update repository versions for Kayobe
  hosts: localhost
  gather_facts: True
  vars:
    kayobe_config_repo_path: ""
    kayobe_pulp_repo_versions_path: "{{ (kayobe_config_repo_path ~ '/etc/kayobe/pulp-repo-versions.yml') | realpath }}"
    kayobe_pulp_repo_versions_dest: "{{ kayobe_pulp_repo_versions_path }}"
  tasks:
    - name: Set a fact about updated Kayobe Pulp repository versions
      vars:
        kayobe_var_name: "{{ 'stackhpc_pulp_repo_' ~ item.key ~ '_version' }}"
        version: "{{ test_pulp_repository_rpm_repo_versions.get(item.key, test_pulp_repository_deb_repo_versions.get(item.key, item.value)) }}"
      set_fact:
        updated_kayobe_pulp_repo_versions: "{{ updated_kayobe_pulp_repo_versions | default({}) | combine({kayobe_var_name: version}) }}"
      loop: "{{ query('dict', kayobe_pulp_repo_versions) }}"
      loop_control:
        label: "{{ item.key }}"

    - name: "Write updated versions to {{ kayobe_pulp_repo_versions_dest }}"
      copy:
        content: |
          ---
          # Do not edit! This file is autogenerated by Ansible.
          {{ updated_kayobe_pulp_repo_versions | to_nice_yaml }}
        dest: "{{ kayobe_pulp_repo_versions_dest }}"
        mode: 0755
